# Generated by Django 3.2.6 on 2021-08-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_alter_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='img',
            new_name='img1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='item',
            name='long_description',
            field=models.TextField(default='long test description'),
        ),
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.TextField(default='short test description'),
        ),
    ]
